modLoader = "javafml"
loaderVersion = "[37,)"
license = "All Rights Reserved"

[[mods]]
modId = "ironbookshelves"
version = "1.17.1-1.0.0-forge"
displayName = "Iron Bookshelves"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/iron-bookshelves"
logoFile = "logo.png"
authors = "jahirtrap"
description = "Bookshelves with more enchantment power"
itemIcon = "ironbookshelves:diamond_bookshelf"

[[dependencies.ironbookshelves]]
    modId = "forge"
    mandatory = true
    versionRange = "[37,)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.ironbookshelves]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[1.17.1,1.18)"
    ordering = "NONE"
    side = "BOTH"
