modLoader = "javafml"
loaderVersion = "[43,)"
license = "All Rights Reserved"

[[mods]]
modId = "ironbookshelves"
version = "${file.jarVersion}"
displayName = "Iron Bookshelves"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/iron-bookshelves"
logoFile = "logo.png"
authors = "jahirtrap"
description = "Bookshelves with more enchantment power"
itemIcon = "ironbookshelves:diamond_bookshelf"

[[dependencies.ironbookshelves]]
    modId = "forge"
    mandatory = true
    versionRange = "[43,)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.ironbookshelves]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[1.19,1.20)"
    ordering = "NONE"
    side = "BOTH"
